### ISSUE TITLE
Add TypeScript typings

### ISSUE THREAD

**Issue by antonsamper** [emotion-js/facepaint#18]
I'm seeing the following error in my TypeScript project:
```
Could not find a declaration file for module 'facepaint'.
'.../node_modules/facepaint/dist/index.cjs.js' implicitly has an 'any' type.
```

Could you submit the typings to DefinitelyTyped?

**Comment by antonsamper** [comment]
Curtesy of @DogPawHat 🎉

https://github.com/DogPawHat/nebulous-dinner/blob/480069c522a42a7f605c6a4ab1726ed7237da0cd/facepaint.d.ts

@DogPawHat @mitchellhamilton  - do you mind if I submit the type definition to DefinitelyTyped?

**Comment by muhajirdev** [comment]
That would be great @antonsamper.
+1 for this

**Comment by alecmolloy** [comment]
Is this being done? I'm happy to make a PR using the shared types if needed. Would badly like to have typings for facepaint. :)

**Comment by antonsamper** [comment]
This has now been merged so it should be available soon

**Comment by antonsamper** [comment]
`npm i -D @types/facepaint`
