### ISSUE TITLE
Same numbers simplify selector and lose specificity

### ISSUE THREAD

**Issue by kirkstrobeck** [emotion-js/facepaint#6]
Given

```js
const styles1 = css(mq({ marginTop: [1, 2] }));
const styles2 = css(mq({ marginTop: [500, 500] }));
cx(styles1, styles2)
```

`marginTop` should be `500`, but it is `2`

---

See https://codesandbox.io/s/k2qzrq2lm7

**Comment by kirkstrobeck** [comment]
https://github.com/emotion-js/facepaint/pull/5 may close this as well

**Comment by tkh44** [comment]
Could you add this as test case in #5's PR? It would be nice to know if it does close it.
